- name: Login
  uses: docker/login-action@v3
  with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}

- name: Push
  run: |
    docker tag myapp ghcr.io/legendairy/myapp:latest
    docker push ghcr.io/legendairy/myapp:latest
